- name: Configure MISO
  hosts: misoservers
  become: true
  tasks:
#    - name: Update apt Cache
#      apt: update_cache=yes cache_valid_time=3600

#    - name: install openjdk-7
#      apt: name=openjdk-7-jdk state=present install_recommends=yes

    - name: install tomcat8
      apt: name=tomcat8

    - name: install nginx
      apt: name=nginx

    - name: install xmlstarlet
      apt: name=xmlstarlet

    - name: install maven
      apt: name=maven

    - name: install python
      apt: name=python

    - name: install python-lxml
      apt: name=python-lxml

    - name: install mysql-server
      apt: name=mysql-server

    - name: install python-mysqldb
      apt: name=python-mysqldb

    - name: Start the MySQL service
      action: service name=mysql state=started

    - mysql_db: name=miso state=present collation=utf8_general_ci encoding=utf8

    - mysql_user: name=misouser host="%" password=12345 priv=miso.*:ALL state=present

    - name: Restart the MySQL service
      action: service name=mysql state=restarted enabled=true

    - name: Download and untar flyway
      unarchive: src=files/flyway-commandline-4.0.1.tar.gz dest=/home/miso copy=yes

    - name: Create symlink to flyway
      file: src=/home/miso/flyway-4.0.1 dest=/home/miso/flyway state=link


    - name: copy MISO db config file
      copy: src=files/ROOT.xml dest=/etc/tomcat8/Catalina/localhost/ROOT.xml

    - name: copy Tomcat config file
      copy: src=files/tomcat8 dest=/etc/default/tomcat8

    - name: Make MISO storage directory
      file: >
        path=/storage/miso
        state=directory
        owner=tomcat8
        group=tomcat8
        mode=0755

    - name: Download and untar MISO properties
      unarchive: >
        src=files/miso_userspace_properties.tar.gz
        dest=/storage/miso copy=yes
        owner=tomcat8
        group=tomcat8
        mode=0755

    - name: download jndi-file-factory
      get_url: >
        url=http://hasbanana.co.uk/maven/repo/uk/ac/ebi/fgpt/jndi-file-factory/1.0/jndi-file-factory-1.0.jar
        dest=/var/lib/tomcat8/lib/
        owner=tomcat8
        group=tomcat8
        mode=0444

    - name: download mysql-connector-java
      maven_artifact: >
        group_id=mysql
        artifact_id=mysql-connector-java
        version=5.1.38
        dest=/var/lib/tomcat8/lib/

    - name: Change mysql-connector-java ownership
      file: >
        path=/var/lib/tomcat8/lib/mysql-connector-java-5.1.38.jar
        owner=tomcat8
        group=tomcat8
        mode=0444

    - name: copy MISO war
      copy: >
        src=/miso-lims/miso-web/target/ROOT.war
        dest=/var/lib/tomcat8/webapps/

    - name: Change MISO war ownership
      file: >
        path=/var/lib/tomcat8/webapps/ROOT.war
        owner=tomcat8
        group=tomcat8
        mode=0444

    - name: Remove ROOT war directory
      shell: rm -rf /var/lib/tomcat8/webapps/ROOT

    - name: copy flyway runner
      copy: >
        src=files/miso-install.sh
        dest=/home/root/

    - name: Run flyway
      shell: >
        cd /home/root;
        bash ./miso-install.sh develop

# See https://github.com/docker/docker/issues/6800 : cannot start tomcat in docker CMD
#    - name: Start Tomcat
#      action: service name=tomcat8 state=started enabled=true

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default

    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: copy index.HTML
      template: >
        src=templates/index.html.j2
        dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
